// Code generated by cmd/gen/main.go; DO NOT EDIT.

package sdk

import (
	"context"
	"net/http"
)

// Ping calls the /ping endpoint using the Get method.
func (c *Client) Ping(ctx context.Context) (*http.Response, error) {
	req, err := c.newRequest(ctx, http.MethodGet, "/ping", nil)
	if err != nil {
		return nil, err
	}
	return c.httpClient.Do(req)
}
